/* Content sourced verbatim/near-verbatim from: michaelallencompany.com (company), MAC Digital Products Hub.html (hub),
   WayFinder Storefront v05.html (storefront), and the latest 1-pagers: NSCLC v06, HF v05, RA v06, OBS v06. */
window.MAC = {
company:{
  tagline:`We derive deeper insights to help healthcare companies make better decisions.`,
  hero:`From pipeline to inline, we empower brands to reach their full potential by transforming research and data into real insights, driving long-term impact.`,
  heroSub:`Explore our difference, or request a bid for your project needs.`,
  nav:[`About Us`,`Our Market Research Solutions`,`Our Market Access Solutions`,`Our Expertise`,`Careers`],
  pillars:[
    {t:`Innovative Research Technology`,d:`SAPPHIRE® is our latest and fastest growing platform supporting brand health tracking.`},
    {t:`Market Access Expertise`,d:`Tailored solutions, supported by extensive payer network.`},
    {t:`Proven Record of Excellence`,d:`Worked with 85% of the Top 20 Global Pharma Companies.`},
    {t:`Experts in Analytics and Integration`,d:`Insights uncovered using both primary research and real world data.`}],
  difference:[
    {t:`Proven Record of Excellence`,d:`For over 40 years, we’ve been a trusted advisor to the world’s leading companies, delivering results through top talent, client trust, and industry expertise.`},
    {t:`Focus on Biopharma`,d:`We serve a single industry – biopharmaceuticals, focusing specifically on sales and marketing, and driving success through decades of excellence.`},
    {t:`Innovative Research Technology`,d:`We advance research and data collection tech for high-quality analyses, transforming insights with innovative technology and global expertise.`},
    {t:`High Touch, with Global Reach`,d:`Our projects span 40+ countries and are always managed by an Executive and staffed with seasoned in-house consulting staff (no off-shoring).`},
    {t:`Extensive Therapeutic Area`,d:`With expertise in 100+ therapeutic areas, our comprehensive solutions address over 100 conditions with significant focus on oncology and orphan diseases.`},
    {t:`Experts in Analytics and Integration`,d:`Worked with 85% of the Top 20 Global Pharma Companies.`}],
  stats:[
    {v:`0%`,l:`reliance on off-shore resources`},
    {v:`[X]%`,l:`consulting staff with degrees from ivy-league schools`},
    {v:`[X]%`,l:`consulting staff with advanced degrees (MA+)`},
    {v:`[X]%`,l:`projects from repeat customers`},
    {v:`[X]%`,l:`projects managed by Senior Leadership`},
    {v:`[X] yrs`,l:`average bio-pharma experience at executive level`}],
  contact:{email:`info@michaelallencompany.com`,phone:`+1.203.662.5100`,fax:`+1.203.662.5180`,address:`30 Old Kings Highway South, Darien, CT 06820`}
},
hub:{
  eyebrow:`Digital Intelligence Portfolio`,
  title:`Strategic Intelligence, Built to Scale`,
  lead:`Modular, productized intelligence tools designed to support commercial, access, and portfolio decision‑making for biopharma leaders.`,
  stats:[{v:`85%`,l:`Top 20 Pharma Clients`},{v:`40+`,l:`Countries Covered`},{v:`Executive`,l:`In-House Staffing`}],
  suiteLead:`First-class digital intelligence tools built on verified market access and oncology mapping methodologies.`,
  wayfinder:{tag:`Market Intelligence`,d:`A strategic intelligence product delivering standardized market and opportunity overviews to support early decision-making.`},
  oncmap:{d:`[OncMap description]`},
  roadmap:{t:`More Products Coming`,d:`Our digital product portfolio continues to expand across indications, data types, and strategic use cases.`,module:`Future Intelligence Module`,slots:[`Pipeline Strategy`,`Access Optimization`,`Commercial Planning`]},
  arch:{eyebrow:`Ecosystem Architecture`,t:`Structured Core Methodologies`,d:`Designed like modern premium modular suites, our digital intelligence tools are built upon a validated, standardized sequence of analytical frameworks. This structural consistency guarantees unassailable credibility and seamless comparability across every commercial, access, and pipeline module.`,
    feats:[{t:`Innovative Technology`,d:`Standardized, automated visual layouts.`},{t:`Access Expertise`,d:`Deep systemic pipeline mapping.`},{t:`Proven Record`,d:`Trusted by 85% of Top 20 Global Pharma.`},{t:`Advanced Analytics`,d:`Synthesizing siloed data layers seamlessly.`}]},
  methods:[`ViewFinder® Epidemiology / Sizing`,`ViewFinder® Patient Journey`,`ViewFinder® Decision Hierarchy`,`ViewFinder® Market Map`,`ViewFinder® Segmentation`,`ViewFinder® Demand Study`,`ViewFinder® Choice Based Drivers`,`ViewFinder® Forecast Model`,`SAPPHIRE® Tracking`]
},
storefront:{
  eyebrow:`Strategic Intelligence Platform`,sub:`Therapeutic Area Storefront`,
  lead:`Explore comprehensive therapeutic area overviews ranked by MASM Attractiveness Scores. Each profile distills market sizing, unmet need, competitive white space, and payer access into an actionable strategic lens.`,
  stats:[{v:`56+`,l:`Pipeline Assets`},{v:`8`,l:`NDA/BLA Filings`},{v:`>$60B`,l:`Addressable Mkt`}],
  cats:[`Oncology`,`Cardiovascular`,`Cardiometabolic`,`Immunology`,`Rare Disease`],
  tips:{market:`Evaluates total addressable market value, revenue trajectory, and projected CAGR. Higher scores indicate larger commercial opportunities.`,
        unmet:`Quantifies residual medical burden — treatment gaps, mortality, and progression despite current therapies.`,
        whitespace:`Measures competitive density: approved therapies, active Phase 3 trials, and biosimilar saturation. Lower scores = more crowded.`,
        access:`Assesses payer environment — formulary placement, step therapy requirements, prior authorization, and Part D exposure.`}
},
tiers:{High:`Strong opportunity — prioritize for pipeline investment, in-licensing, or M&A`,Moderate:`Conditional opportunity — attractive with differentiated asset or favorable timing`},
pillarKeys:[`market`,`unmet`,`whitespace`,`access`],
pillarLabels:{market:`Market Sizing`,unmet:`Unmet Need`,whitespace:`White Space`,access:`Access Ease`},
followUp:[
  {t:`KOL Expert Interviews`,d:`Leveraging one of the largest global HCP panels for rapid qualitative validation.`},
  {t:`On-Demand RWD Analytics`,d:`Leveraging one of the largest US healthcare data coverages for robust longitudinal cohorts.`},
  {t:`And More`,d:`Custom advisory boards, payer research, and bespoke commercial landscape assessments.`}],
tas:[
{id:`nsclc`,name:`Non-Small Cell Lung Cancer`,abbr:`NSCLC`,cat:`Oncology`,masm:73,tier:`Moderate`,updated:`Q3 2026`,
 short:`NSCLC remains the crown jewel of oncology markets. Future value creation lies in the post-IO refractory setting through ADCs and next-generation bispecifics.`,
 pillars:{market:{v:`Massive Blockbuster`,s:95,d:`Market value >$25B globally. Multiple high-cost specialty therapies dominate as targeted biologic and ADC adoption expands.`},
  unmet:{v:`Critical Gaps`,s:82,d:`Severe clinical burden remains. Most patients with advanced disease ultimately progress after IO and targeted TKIs, though timing and resistance mechanisms vary.`},
  whitespace:{v:`Saturated / Commoditized`,s:25,d:`Heavily crowded with 100+ active Phase 3 trials. Generic chemo and entrenched IOs dominate, making the pipeline exceptionally competitive.`},
  access:{v:`Moderate Friction`,s:55,d:`Favorable oncology access, but strict biomarker/NGS gatekeeping and clinical pathway restrictions limit seamless adoption.`}},
 summary:[`NSCLC remains the crown jewel of oncology markets, but the competitive landscape is entering a period of significant disruption. Two forces are reshaping the market: (1) the approaching loss of exclusivity of Keytruda, which is expected to increase biosimilar competition, compress immunotherapy pricing, and raise the bar for clinical differentiation; and (2) the emergence of next-generation PD-(L)1 × VEGF bispecifics such as ivonescimab and BNT327, which represent the first credible challenge to the long-standing PD-1 treatment paradigm.`,
  `As a result, future value creation is increasingly shifting away from broad, undifferentiated attempts to displace Keytruda in frontline populations. Instead, the most attractive opportunities reside in biomarker-defined subsegments, post-PD-1 refractory disease, and highly differentiated platforms capable of delivering meaningful overall survival improvements. For ADCs, demonstrating superiority over docetaxel while avoiding severe ILD remains the critical commercial hurdle; for immunotherapies, proving clear benefit beyond established PD-1 backbones will determine long-term market relevance.`],
 s1:`Market Sizing & Biomarkers`,
 stats:[{v:`~200k`,l:`Incident US Cases/Yr`,src:`SEER Cancer Stat Facts (2025)`},{v:`~50%`,l:`Actionable Mutations`,src:`JTO Non-Squamous Profiling (2024)`},{v:`+9.2%`,l:`Rev CAGR ('24-'26)`,src:`Evaluate Pharma, 2026 Estimate`},{v:`~28%`,l:`5-Year Survival`,src:`American Cancer Society (2025)`}],
 split:{t:`Histology Split`,parts:[[`Non-Squamous`,75],[`Squamous`,25]],note:`Squamous heavily restricts VEGF/anti-angiogenic use due to high risks of fatal hemoptysis.`},
 tags:{t:`Key Actionable Biomarkers`,items:[`EGFR (~15%)`,`KRAS G12C (~13%)`,`ALK (~4%)`,`Exon 20 (~2%)`,`ROS1 (~1-2%)`]},
 tags2:{t:`Top Comorbidities & Complications`,items:[`COPD / Emphysema ~40-45%`,`CNS / Brain Metastases (at Dx) ~30%`]},
 insight:`Because ~30% of EGFR/ALK-mutated NSCLC patients present with or develop CNS metastases, blood-brain barrier (BBB) penetrance is a mandatory gating requirement for any next-generation Targeted Kinase Inhibitor (TKI) to achieve commercial viability.`,
 s2:`Post-IO Resistance, Toxicity & Paradigms`,
 unmet:[{t:`Early-Stage Curative vs. Metastatic`,d:`The most lucrative paradigm shift is moving systemic therapies (IO, TKIs) into the neoadjuvant/adjuvant (Stage I-III) setting to prevent recurrence. While metastatic disease focuses on life extension (PFS/OS), the early-stage market demands curative intent (pCR, EFS) with substantially lower tolerance for chronic toxicity.`},
  {t:`The Post-PD-1 “Chemo Upgrade” (ADCs)`,d:`While PD-1/PD-L1 inhibitors revolutionized 1L care, the vast majority of patients eventually progress. The 2L/3L setting relies on docetaxel (ORR ~15%). ADCs are rapidly acting as “smart chemotherapies” to upgrade this salvage line, but the risks of Interstitial Lung Disease (ILD) and pneumonitis cap their real-world utility.`,src:`Lancet Oncology (2025) & ESMO Safety Reports`},
  {t:`Acquired TKI Resistance`,d:`Patients on targeted therapies such as osimertinib and KRAS G12C inhibitors frequently progress. Resistance can be mediated by secondary mutations (e.g., C797S), bypass signaling, histologic transformation, or unknown mechanisms — bypassing these is a focus of next-gen degraders and combo-ADCs.`,src:`Clinical Cancer Research (2024)`}],
 pipeLead:`The NSCLC developmental pipeline is characterized by a fundamental shift away from rudimentary small-molecule inhibitors toward highly engineered, multi-domain biotherapeutics.`,
 pipeline:[[`Ivonescimab`,`PD-1 x VEGF`,`Akeso / Summit`,`Ph 3 HARMONi — BLA`,`U.S. BLA accepted for ivonescimab + platinum-doublet chemotherapy in EGFR-mutated advanced non-squamous NSCLC after 3rd-gen EGFR-TKI progression; FDA PDUFA Nov 14, 2026.`],
  [`Pumitamig (BNT327)`,`PD-L1 x VEGF-A`,`BioNTech / BMS`,`Ph 3 ROSETTA Lung-01/02`,`Initiating 8 global Phase 3 trials.`],
  [`Sacituzumab tirumotecan`,`TROP2 ADC`,`Merck / Kelun`,`Ph 3 OptiTROP / TroFuse`,`Massive global development program across 15+ trials.`],
  [`Datopotamab deruxtecan`,`TROP2 ADC`,`AstraZeneca / Daiichi`,`Ph 3 TROPION-Lung`,`Expansion readouts addressing ILD concerns and OS endpoints.`],
  [`Zidesamtinib (NVL-520)`,`ROS1 TKI`,`Nuvalent`,`NDA`,`Brain-penetrant, ROS1-selective TKI; FDA PDUFA target Sep 18, 2026.`],
  [`Daraxonrasib (RMC-6236)`,`RAS(ON) Multi`,`Revolution Medicines`,`Ph 3`,`RASolute 302 readout expected 1H 2026.`]],
 algo:{note:`Simplified flow; actual sequencing heavily depends on actionable biomarker status and PD-L1 TPS scores.`,rows:[[`Actionable Driver w/ Approved 1L Targeted Rx`,`Matched 1L Targeted Regimen`,`2L: Selected Approved Options / Clinical-Trial Pathways`],[`Biomarker Negative`,`1L IO ± Chemo`,`2L: Selected Approved Options / Clinical-Trial Pathways`]]},
 s4:`Hurdles & Payer Landscape`,
 payer:[{t:`Biomarker / NGS Gatekeeping`,d:`Payers aggressively deny targeted therapies if precise molecular testing (e.g., EGFR, ALK, ROS1, MET, RET) is not fully documented. Tissue exhaustion remains a logistical barrier.`},
  {t:`Clinical Pathways (Value-Based Care)`,d:`If a new drug is not designated as “on-pathway” — often determined by price/efficacy ratios — physician adoption is severely blunted.`},
  {t:`Site of Care & “Buy-and-Bill” Economics`,d:`IV therapies (ADCs, IO) run through Part B buy-and-bill; oral TKIs face Part D hurdles where high out-of-pocket costs drive prescription abandonment.`},
  {t:`340B Margin Pressures`,d:`Steep mandatory 340B discounts (often >50% off WAC) compress gross-to-net revenues for high-cost infusions like ADCs.`}],
 mix:{parts:[[`Medicare (Part B/D)`,65],[`Commercial`,35]],note:`Median age of NSCLC diagnosis is 70, leading to massive Medicare exposure and high sensitivity to IRA price negotiations.`},
 radar:[{k:`Upcoming Catalyst`,t:`Ivonescimab Global Data vs Keytruda`,d:`BLA accepted (PDUFA Nov 14, 2026). China-only HARMONi-6 showed OS benefit in 1L squamous NSCLC (27.9 vs 23.7 mo; HR 0.66); global 1L head-to-head data remain outstanding.`},
  {k:`Valuation Benchmark`,t:`Pfizer acquires Seagen ($43B)`,d:`Cemented ADCs as the structural foundation for the next decade of solid tumor/NSCLC treatment.`},
  {k:`Policy Headwind`,t:`IRA Medicare Price Negotiations`,d:`Given 65% Medicare exposure, oral TKIs and older IO agents are prime targets for Maximum Fair Price negotiations.`},
  {k:`Regulatory Weather`,t:`Project FrontRunner & OS Demands`,d:`FDA’s Oncology Center of Excellence is pushing back on accelerated approvals based solely on ORR/PFS.`}]},

{id:`hf`,name:`Heart Failure`,abbr:`HF`,cat:`Cardiovascular`,masm:67,tier:`Moderate`,updated:`Q2 2026`,
 short:`The HF market has matured rapidly with the universal “Four Pillars” of GDMT. Strategy has pivoted toward precision cardiometabolic phenotypes and obesity-driven HFpEF.`,
 pillars:{market:{v:`Massive Blockbuster`,s:88,d:`Market value >$15B globally with >6.7M US prevalence. Driven by high-cost specialty therapy adoption and expanding metabolic indications.`},
  unmet:{v:`Critical Gaps`,s:78,d:`Severe clinical burden remains in Worsening HF. Toxicity/tolerability limits current polypharmacy options.`},
  whitespace:{v:`Saturated / Commoditized`,s:22,d:`Crowded field with established “Four Pillars” of GDMT. Requires new assets to target highly specific phenotypes.`},
  access:{v:`Significant Barriers`,s:30,d:`Enormous prevalent population lacking strict later-line gating triggers massive budget-impact scrutiny. Heavy Part D exposure.`}},
 summary:[`The Heart Failure (HF) market has matured rapidly with the universal establishment of the “Four Pillars” of Guideline-Directed Medical Therapy (GDMT) for HFrEF. As broad population treatments face genericization and strict IRA price negotiations, pharmaceutical strategy has aggressively pivoted toward precision cardiometabolic phenotypes.`,
  `Future value generation is concentrated in treating obesity-driven HFpEF via next-generation incretins (GLP-1s), intercepting worsening heart failure (WHF) events, and deploying targeted interventions (RNAi, CRISPR, myosin modulators) for rare cardiomyopathies like ATTR-CM and HCM.`],
 s1:`Market Sizing & Phenotypes`,
 stats:[{v:`~6.7M`,l:`Total US Prevalence`,src:`AHA Heart Disease Statistics (2025)`},{v:`~25%`,l:`30-Day Readmission`,src:`JACC Quality & Outcomes (2025)`},{v:`+4.8%`,l:`Rev CAGR ('24-'26)`,src:`Evaluate Pharma, 2026 Estimate`},{v:`50%`,l:`5-Year Mortality`,src:`European Heart Journal (2024)`}],
 split:{t:`Ejection Fraction Split`,parts:[[`HFrEF`,45],[`HFpEF`,50],[`mrEF`,5]],note:`HFpEF represents the fastest growing segment, historically underserved until SGLT2i approvals.`},
 tags:{t:`Key Precision Targets`,items:[`ATTR-CM (~15% of older HFpEF)`,`Obesity-HFpEF phenotype`,`Hypertrophic Cardiomyopathy (HCM)`]},
 tags2:{t:`Top Comorbidities (The Cardio-Renal-Metabolic Axis)`,items:[`Chronic Kidney Disease (CKD) ~50%`,`Type 2 Diabetes (T2D) ~45%`]},
 insight:`Cardiovascular, Renal, and Metabolic (CRM) diseases are no longer treated in silos. Payers and guidelines mandate therapies like SGLT2is and GLP-1s because they simultaneously treat the heart, protect the kidneys, and manage weight/glucose. Single-organ therapies face steep commercial headwinds.`,
 s2:`Worsening Events, Polypharmacy & HFpEF`,
 unmet:[{t:`The Worsening Heart Failure (WHF) Cycle`,d:`Despite maximal GDMT, patients experience acute decompensation requiring hospitalization or urgent IV diuretics. Each WHF event irreversibly damages myocardial tissue and drastically reduces survival.`},
  {t:`HFpEF Efficacy Ceilings`,d:`While SGLT2 inhibitors provide the first real mortality/hospitalization benefit for HFpEF, symptom burden and exercise intolerance remain profoundly high. True structural disease modification remains elusive.`,src:`ACC Heart Failure Guidelines Update (2025)`},
  {t:`Polypharmacy and Tolerability Limits`,d:`Hypotension, hyperkalemia, and worsening renal function prevent over 60% of patients from ever reaching optimal target doses of quadruple therapy.`,src:`CHAMP-HF Registry Data Analysis (2024)`},
  {t:`Underdiagnosis of ATTR-CM`,d:`ATTR-CM is heavily underdiagnosed in elderly HFpEF. Stabilizers only slow progression; there is an urgent need for therapies that actively clear deposited amyloid fibrils.`,src:`Journal of Cardiac Failure (2025)`}],
 pipeLead:`The cardiovascular pipeline is pivoting from broad hemodynamic modulators toward highly targeted therapies: genetic silencing for amyloidosis, metabolic optimization via incretin mimetics, and direct sarcomere modulation.`,
 pipeline:[[`Semaglutide (Wegovy)`,`GLP-1 Agonist`,`Novo Nordisk`,`Pending FDA (2H 2026)`,`Dedicated HFpEF indication pending following FLOW and SOUL data.`],
  [`Tirzepatide`,`Dual GIP/GLP-1`,`Eli Lilly`,`Post-SUMMIT FDA Review`,`Reduced risk of WHF events by 38% in adults with HFpEF and obesity.`],
  [`Acoramidis`,`TTR Stabilizer`,`BridgeBio / Bayer`,`Launch`,`Next-gen stabilizer to challenge Vyndaqel dominance in ATTR-CM.`],
  [`Aficamten`,`Myosin Inhibitor`,`Cytokinetics`,`NDA Review (HCM)`,`Targeting obstructive HCM; potentially cleaner REMS profile than Camzyos.`],
  [`NTLA-2001`,`In Vivo CRISPR`,`Intellia / Regeneron`,`Ph 3 MAGNITUDE`,`One-time gene editing therapy aiming for functional cure of ATTR-CM.`],
  [`Ziltivekimab`,`IL-6 Inhibitor`,`Novo Nordisk`,`Ph 3 HERMES`,`Targeting systemic inflammation in HFpEF/HFmrEF. Completion mid-2027.`]],
 algo:{note:`Simplified sequence; specific pathways heavily dictated by Ejection Fraction and clinical phenotype.`,rows:[[`HFrEF (Standard)`,`Four Pillars (ARNI/BB/MRA/SGLT2)`,`WHF Event: Add sGC stimulator / IV Iron`],[`HFpEF (Obesity)`,`SGLT2i Foundation`,`Add GLP-1/GIP (Incretins)`]]},
 s4:`IRA Impacts & Payer Landscape`,
 payer:[{t:`The Population Budget Paradox`,d:`With nearly 7 million US patients and no narrowly defined later-line setting, any broad-label therapy triggers an immediate budget impact, forcing payers to throttle utilization regardless of clinical superiority.`},
  {t:`GLP-1 Access Dynamics & The SGLT2 Precedent`,d:`Enthusiasm for GLP-1s in obesity-driven HFpEF will increase payer scrutiny and Prior Authorization walls, mirroring the multi-year trajectory SGLT2 inhibitors endured.`},
  {t:`The IRA Medicare Threat`,d:`Entresto and Farxiga were selected for the first round of CMS Maximum Fair Price negotiations, with mandated price cuts taking effect in 2026.`}],
 mix:{parts:[[`Medicare (Part D Focus)`,75],[`Commercial`,20]],note:`HF is primarily a disease of the elderly. Heavy Medicare Part D reliance makes IRA out-of-pocket caps and CMS price negotiations profoundly disruptive.`},
 radar:[{k:`Upcoming Catalyst`,t:`CRISPR In-Vivo Data in Cardiology`,d:`Intellia’s Phase 3 MAGNITUDE trial will test whether one-time in-vivo gene editing can achieve a functional cure in ATTR-CM.`},
  {k:`Valuation Benchmark`,t:`The Cardiometabolic Land Grab`,d:`Novo, Lilly and AstraZeneca are acquiring assets bridging heart failure, obesity and CKD.`},
  {k:`Policy Headwind`,t:`Patent Cliffs & MFP Enforcement`,d:`Entresto and Farxiga face both MFP caps and impending generic LOE walls.`},
  {k:`Emerging Pipeline`,t:`Targeting Cardiac Inflammation (IL-6)`,d:`Ziltivekimab aims to prove that treating inflammation directly can reduce HF hospitalizations.`}]},

{id:`ra`,name:`Rheumatoid Arthritis`,abbr:`RA`,cat:`Immunology`,masm:63,tier:`Moderate`,updated:`August 2026`,
 short:`The RA paradigm is undergoing structural transformation. The pipeline pivots from broad cytokine blockade toward targeted intracellular nodes, bispecific modulators, and CAR-T cell therapies aimed at immune reset.`,
 pillars:{market:{v:`Large Growing Market`,s:70,d:`Large, mature specialty market; US prevalence is commonly estimated at ~1.3–1.5M adults, with substantial global disease burden.`},
  unmet:{v:`Critical Gaps`,s:68,d:`A meaningful subset remain difficult-to-treat after multiple advanced therapies; safety risk stratification constrains use of current JAK inhibitors.`},
  whitespace:{v:`Crowded Field`,s:20,d:`MTX remains foundational and preferred TNF biosimilars intensify access pressure; new entrants need clear efficacy, safety, durability, or delivery differentiation.`},
  access:{v:`Significant Barriers`,s:22,d:`Many US plans use csDMARD and preferred-product step therapy, but sequencing requirements vary materially by payer and formulary.`}},
 summary:[`The Rheumatoid Arthritis (RA) market is mature, crowded, and increasingly shaped by biosimilar competition and tighter safety-based treatment selection. MTX remains foundational, while biologic and targeted synthetic DMARDs provide multiple effective options after inadequate csDMARD response. Current JAK inhibitors retain an important role, but FDA boxed warnings and EULAR risk-factor guidance limit broad use in higher-risk patients.`,
  `The most differentiated RA innovation is moving toward more selective immune modulation: pathogenic T-cell modulation/depletion (e.g., rosnilimab); B-cell-directed immune reset strategies spanning trispecific engagers and CD19 CAR-T; upstream immune targets including TL1A and CD40; and selective intracellular signaling such as RIPK1. The commercial bar is high.`],
 s1:`Market Sizing & Phenotypes`,
 stats:[{v:`~1.3–1.5M`,l:`Total US Prevalence`,src:`Hunter et al., Rheumatol Int (2017); Xu & Wu (2021)`},{v:`~40%`,l:`Inadequate Response to Initial TNFi`,src:`Taylor et al., Rheumatol Ther (2022)`},{v:`+3.5%`,l:`US Market CAGR ('25-'35)`,src:`Decision Advisors, US RA Therapeutics Forecast (2025)`},{v:`1.33`,l:`MACE HR vs TNFi*`,src:`ORAL Surveillance, NEJM (2022); CV-risk-enriched`}],
 split:{t:`Serotype Split`,parts:[[`Seropositive (RF+ / CCP+)`,75],[`Seronegative`,25]],note:`RF/ACPA positivity is associated with a higher likelihood of erosive disease, but treatment escalation remains driven primarily by disease activity, response, comorbidity, and prior therapy.`},
 tags:{t:`Key Investigational Targets`,items:[`PD-1 / Pathogenic T Cells`,`CD19 / B-Cell Depletion`,`CD40 / Co-stimulation`,`TL1A`,`RIPK1`]},
 tags2:{t:`Pathological Drivers & Biomarkers`,items:[`TNF-alpha`,`IL-6`,`T-cell Co-stimulation / PD-1 Axis`,`B-cell / CD19-CD40 Axis`,`RF / Anti-CCP (ACPA)`]},
 insight:`The strategic opportunity is concentrated in patients who remain active after multiple b/tsDMARDs. Differentiation increasingly depends on a new mechanism plus a meaningful advantage in depth or durability of response, safety, or treatment burden — not simply placebo-controlled activity.`,
 s2:`Toxicity Limits, Refractory Disease & Tapering`,
 unmet:[{t:`Safety Constraints on Current JAK Inhibitors`,d:`FDA boxed warnings cover serious cardiovascular events, malignancy, thrombosis, and death. EULAR 2025 recommends JAK inhibitors be considered only with pertinent risk factors taken into account.`},
  {t:`Broad Immunosuppression & Infection Risk`,d:`The unmet need is to preserve efficacy while improving selectivity, infection risk, tolerability, and long-term treatment burden.`},
  {t:`Loss of Efficacy & Redundant Pathways`,d:`Primary inadequate response and secondary loss of response remain important clinical problems, supporting therapies that engage different immune biology.`},
  {t:`Durable Drug-Free Remission Remains Uncommon`,d:`There is a major unmet need for therapies capable of durable disease control with less continuous treatment exposure; permanent cure has not been established.`}],
 pipeLead:`The RA pipeline is diversifying beyond established cytokine and JAK pathways toward pathogenic T-cell modulation, B-cell-directed immune reset, upstream immune signaling (TL1A/CD40), and selective intracellular nodes such as RIPK1.`,
 pipeline:[[`Rosnilimab`,`PD-1 Agonist / T-cell Depleter`,`First Tracks Biotherapeutics`,`Phase 2b Completed (RENOIR)`,`Positive Phase 2b RA efficacy, safety and translational proof-of-mechanism; End-of-Phase 2 FDA meeting completed.`],
  [`Afimkibart (RG6631)`,`Anti-TL1A mAb`,`Roche / Genentech`,`Phase 2b (dRAvite)`,`Recruiting moderate-to-severe RA patients after TNF and/or JAK inhibitor failure.`],
  [`BMS-986353 (CC-97540)`,`CD19 CAR-T`,`Bristol Myers Squibb`,`Phase 1 (Breakfree-1)`,`Deep B-cell depletion / immune-reset strategy in severe, refractory RA.`],
  [`PIT565`,`CD19×CD3×CD2 Trispecific`,`Novartis`,`Phase 1`,`First-in-class trispecific redirecting T cells toward CD19+ B cells.`],
  [`Abiprubart (KPL-404)`,`Anti-CD40 mAb`,`Kiniksa`,`Phase 2`,`Phase 2 RA proof-of-concept has generated clinical data.`],
  [`SetPoint System`,`Vagal Nerve Stimulation`,`SetPoint Medical`,`FDA Approved`,`Approved July 2025 for moderate-to-severe RA after ≥1 b/tsDMARD.`]],
 algo:{note:`EULAR Treat-to-Target Strategy. US access can further influence sequencing through preferred-product and step-therapy requirements.`,rows:[[`1L Initial`,`csDMARD (Methotrexate) + Short-term Glucocorticoids`,``],[`2L Escalation`,`Add bDMARD (TNF / IL-6; biosimilar where preferred)`,``],[`3L Refractory`,`Switch b/tsDMARD / Novel MOA / Specialty`,``]]},
 s4:`Hurdles, Biosimilars & Access Landscape`,
 payer:[{t:`Typical Payer Step-Edit Flow`,d:`Step 1: Methotrexate (generic) → Step 2: Adalimumab / Infliximab biosimilars → Step 3: Targeted kinase / advanced biologic.`},
  {t:`The Biosimilar Wall`,d:`Adalimumab and infliximab biosimilars have intensified price and formulary competition, raising the access bar for premium-priced novel mechanisms.`},
  {t:`CAR-T Outpatient Logistics`,d:`For one-time immune-reset strategies, benefit must justify upfront treatment, lymphodepletion, monitoring, and site-of-care burden.`}],
 mix:{parts:[[`Commercial`,60],[`Medicare (Part B/D)`,40]],note:`Directional strategic estimate; actual RA payer mix varies by age, product, plan, and dataset.`},
 radar:[{k:`Upcoming Catalyst`,t:`Afimkibart Phase 2b dRAvite`,d:`A test of whether TL1A biology can translate from IBD into a differentiated RA mechanism.`},
  {k:`Valuation Benchmark`,t:`Roche / Telavant TL1A Deal ($7.1B)`,d:`The acquired asset, now afimkibart, has expanded into a Phase 2b RA program.`},
  {k:`Regulatory Weather`,t:`High Clinical Differentiation Bar`,d:`GSK’s otilimab showed limited efficacy despite activity versus placebo.`},
  {k:`Emerging Modality`,t:`SetPoint Neuroimmune Modulation`,d:`FDA approved July 2025; commercial expansion during 2026.`}]},

{id:`obs`,name:`Obesity`,abbr:`OBS`,cat:`Cardiometabolic`,masm:90,tier:`High`,updated:`Q2 2026`,
 short:`The obesity landscape is rapidly evolving from first-wave incretin adoption toward differentiated next-generation weight-management strategies.`,
 pillars:{market:{v:`Massive Blockbuster`,s:null,d:`Global obesity-medicine sales reached approximately $66B in 2025 and are forecast at approximately $92B in 2026, with multiple forecasts exceeding $100B later in the decade.`},
  unmet:{v:`Critical Gaps`,s:null,d:`High to moderate gaps persist among patients seeking durable, clinically supported weight loss, including needs around body-composition quality, GI tolerability, and dosing convenience.`},
  whitespace:{v:`Underserved Market`,s:null,d:`Novo Nordisk and Eli Lilly currently dominate branded incretin-based treatment, but dozens of pipeline assets and future generic/biosimilar pressure may increasingly crowd the space.`},
  access:{v:`Significant Barriers`,s:null,d:`Significant population-level budget impacts continue to drive prior authorization and step therapy barriers. Medicare Part D still excludes drugs used solely for weight loss.`}},
 summary:[`The obesity and cardiometabolic landscape is rapidly evolving from first-wave incretin adoption toward differentiated next-generation weight-management strategies. While high-magnitude weight loss is increasingly achievable, commercial success is shifting beyond absolute efficacy. The key competitive axes are now durability, tolerability, route and frequency of administration, body-composition quality, supply scalability, and outcomes-linked value in comorbid populations (such as cardiovascular disease, OSA, MASH, CKD, and HFpEF).`,
  `While Novo Nordisk and Eli Lilly remain the dominant incumbents, late-stage assets such as retatrutide, CagriSema, orforglipron, MariTide, CT-388, survodutide, ecnoglutide and petrelintide are poised to reshape market segmentation. Label expansion and evidence in high-risk comorbid populations are creating more defensible reimbursement pathways.`],
 s1:`Market Sizing & Phenotypes`,
 stats:[{v:`>100M`,l:`Total US Prevalence`,src:`CDC / NHANES (2026 Update)`},{v:`~20-25%`,l:`Avg. Weight Reduction`,src:`Next-Gen Incretin Phase 3 Benchmarks`},{v:`>$100B`,l:`Late-Decade Forecast`,src:`IQVIA 2026 Outlook; Goldman Sachs 2030 forecast`},{v:`~2/3`,l:`Weight Regain (1 Yr)`,src:`STEP-1 extension; off-treatment follow-up`}],
 split:{t:`Commercial Phenotype Split (Illustrative)`,parts:[[`Obesity + Comorbidities`,45],[`Other`,55]],note:`Payers and Medicare often restrict access based on documented comorbidities (CVD, MASH, OSA).`},
 tags:{t:`Key Pipeline MoAs`,items:[`Tri-Agonists (GLP/GIP/GCG)`,`Amylin Analogs`,`Oral Small Molecules`,`Myostatin/Activin A Inhibitors`]},
 tags2:{t:`Targeted Co-Morbidities (Reimbursement Keys)`,items:[`Heart Failure (HFpEF)`,`MASH/NASH`,`Obstructive Sleep Apnea (OSA)`,`Chronic Kidney Disease`]},
 insight:`A drug achieving ~25% weight loss may still face difficult access discussions if it lacks outcomes evidence in reimbursable comorbidity segments. Payers now prioritize outcome evidence as a critical differentiator for reimbursement and label expansion.`,
 s2:`Quality of Weight Loss, Sarcopenia & Delivery`,
 unmet:[{t:`Quality of Weight Loss & Lean Mass Depletion`,d:`Body-composition substudies show a meaningful share of total weight loss can be lean mass. The framing is quality of weight loss and preservation of functional lean tissue, especially in older or higher-risk populations.`},
  {t:`Gastrointestinal Tolerability & Titration`,d:`GI adverse events remain important drivers of discontinuation and titration complexity, highlighting the need for alternative mechanisms to improve long-term tolerability.`},
  {t:`Route of Administration & Frequency`,d:`Weekly injections pose a high injection burden. The market is pursuing oral small molecules and ultra-long-acting antibodies for monthly or quarterly dosing.`},
  {t:`The “Rebound Effect”`,d:`Discontinuation of incretin therapies leads to substantial weight regain within one year. Therapies that support long-term weight maintenance remain a key research priority.`}],
 pipeLead:`The 2026 pipeline has splintered into distinct competitive lanes: oral convenience, enhanced magnitude via multi-agonists, comorbidity-driven differentiation, and lean-tissue preservation combination strategies.`,
 pipeline:[[`Retatrutide`,`GLP-1/GIP/GCG Tri-Agonist`,`Eli Lilly`,`Ph 3 (TRIUMPH)`,`TRIUMPH-4 reported up to 28.7% average weight reduction at 68 weeks.`],
  [`CagriSema`,`Amylin + GLP-1 Combo`,`Novo Nordisk`,`Ph 3 (REDEFINE)`,`REDEFINE-1 reported 22.7% weight loss (treatment-adherence estimand) and 20.4% regardless of adherence.`],
  [`Orforglipron`,`Oral GLP-1 (Non-Peptide)`,`Eli Lilly`,`Approved / Label-Ready`,`Once-daily oral option; ATTAIN-1 reported 12.4% average weight loss at 72 weeks.`],
  [`MariTide (AMG 133)`,`GIPR Antagonist / GLP-1`,`Amgen`,`Phase 3 Initiation`,`Monthly or less frequent dosing; Phase 2 showed up to ~20% weight loss.`],
  [`CT-388`,`GLP-1/GIP Agonist`,`Roche / Carmot`,`Phase 3 Advancing`,`22.5% placebo-adjusted weight loss at 48 weeks at the highest dose.`],
  [`Petrelintide`,`Amylin Analog`,`Zealand Pharma / Roche`,`Phase 3 Planned`,`Up to 10.7% mean weight loss at week 42 versus 1.7% placebo.`]],
 algo:{note:`MAC Hypothetical Sequence Framework — evolving concept focusing on maintenance, tolerability, and muscle preservation.`,rows:[[`1L Induction`,`SubQ GLP-1/GIP (Wegovy / Zepbound)`,`Rapid weight reduction, but GI tolerability issues persist.`],[`2L Escalation / Plateau`,`Tri-Agonists or Amylin Combos`,`Retatrutide or CagriSema to exceed the 20% efficacy threshold.`],[`Maintenance / Adjunct`,`Oral Incretins + Muscle Preservers`,`Step down to oral orforglipron; add myostatin inhibitors to rescue lean mass.`]]},
 s4:`The Population Budget Paradox & Medicare`,
 payer:[{t:`The Population Budget Paradox`,d:`With over 100 million U.S. adults living with obesity, payers construct rigorous Prior Authorization pathways requiring high-BMI thresholds and documented outcome-linked comorbidities.`},
  {t:`Employer Opt-Outs`,d:`Many large employers have expanded coverage, while some self-funded employers have dropped or restricted coverage to protect near-term budgets.`},
  {t:`Medicare Exclusion (The TROA Battle)`,d:`Part D is prohibited from covering drugs strictly for weight loss, but coverage can occur for another FDA-approved indication such as CV risk reduction or OSA.`}],
 mix:{parts:[[`Commercial (Employer/Plan)`,80],[`Medicare (Via Comorbidities)`,20]],note:`Illustrative MAC access assumption; validate with claims / payer research before use in forecasting.`},
 radar:[{k:`Upcoming Catalyst`,t:`Amgen's MariTide Data`,d:`Will test whether monthly or less frequent dosing can deliver durable weight loss at Phase 3 scale.`},
  {k:`Valuation Benchmark`,t:`Pfizer Acquires Metsera`,d:`Completed November 2025, adding a weekly/monthly GLP-1 RA platform (MET-097i).`},
  {k:`Legislative Weather`,t:`Treat and Reduce Obesity Act (TROA)`,d:`Could expand Medicare access if enacted; a policy-watch item rather than a settled outcome.`},
  {k:`Commercial Threat`,t:`Long-term Genericization of First-Gen Incretins`,d:`Semaglutide patent expiry is beginning outside the U.S. in 2026; U.S. protection extends into the early 2030s.`}]}
]};
